# Generated by Django 2.1.4 on 2018-12-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20181227_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='forum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.Forum'),
            preserve_default=False,
        ),
    ]
